### ISSUE TITLE
add level selection

### ISSUE THREAD

**Issue by miller-time** [miller-time/rust-warrior#5]
prompt for level select in `Game::play`

levels 1 through the current level should be available, current level should be the default and require no input (except `Enter`) to select

consider adding `ui::choose` helper function. Ruby Warrior, for reference:
https://github.com/ryanb/ruby-warrior/blob/03a9e73a7a09ea2b146e4d4abffc49844d6aacbb/lib/ruby_warrior/ui.rb#L32

note: possible semantic conflict with #1 - need to separately keep track of the **current** level and the **selected** level, if the warrior is *earning* abilities and can use the newly earned abilities to repeat earlier levels. alternatively, the warrior can simply lose the new abilities when going back to earlier levels. :thinking: 

note2: why would someone want the ability to replay earlier levels? my guess would be that they think something along the lines of "with my new abilities, now that level will be way easier". so *earning and keeping* is probably better than *losing* in order to fulfill that. also, it would be very annoying if their code panics and they have to change it again just to replay an earlier level.

**Comment by boxofrox** [comment]
An alternative idea. Once you reach the top level, a bonus challenge could be, "Now use all your skills to teach your warrior to fight through all the levels."

I.e. in followup runs, the warrior starts at level 1 and visits all levels without a break and the programmer's goal is to write an AI that can navigate all the levels in succession.

Could eventually upgrade `Game::play` to take a `Challenge` enum so the user can select from a variety of challenges to send their AI against.  E.g.

```rs
enum Challenge {
  Tutorial,  // The current challenge where the player progresses one level at a time.
  Gauntlet,  // The player visits all levels of the Tutorial without breaks.
  Random(u64 /* rng seed */),  // One random level is generated.
  RandomContinuous(u64 /* rng seed */),  // Player runs through random levels without a break until user interrupts, or warrior dies.
}
```

**Comment by miller-time** [comment]
@boxofrox thanks for the suggestion!

I think all of those different game modes would need to build on top of the concept of a level being selected (separate from the current tracking of level progression).

Is this something you wanted to contribute to the project? 

There haven't been a lot of questions from players, so if you don't mind me asking... 

* have you tried playing? was it fun? hard? easy? 
* have you beaten the final level? 

Thanks for the feedback

**Comment by boxofrox** [comment]
> Is this (these challenge modes) something you wanted to contribute to the project?

I would like to, but I've so much on my plate atm, I'm not sure how well I can commit to the effort.  I do plan to dabble with the idea in a fork.  If I reach a state for submitting a PR, I'll definitely do so, even if only for review.

> have you tried playing? was it fun? hard? easy?

Yes.

I enjoyed it.

Hard? I don't think it was hard, but I rarely got the player turn correct the first time.  I even succeeded a level by shooting a captive with an arrow, which seemed weird, due to my buggy code.  I'm a polyglot programmer (C, C++, Java, Rust, Ruby, JS, Lisp, v-lang), so probably too much programming experience to see this as hard as a beginner might.

> have you beaten the final level?

Yes.  I completed the exercise in an evening.

> how did you hear about Rust Warrior?

libs.rs under the games section.  I did the ruby-warrior exercise when I was programming ruby, and this was a pleasant nostalgic jaunt with my current language, Rust.

Cheers.
